---
#Database Tier
- name: MongoDB
  hosts: comp_mongodb
  become: true
  gather_facts: false
  tags: [mongodb]
  roles:
    - mongodb

- name: MySQL
  hosts: comp_mysql
  become: true
  gather_facts: false
  tags: [mysql]
  roles:
    - mysql

- name: RabbitMQ
  hosts: comp_rabbitmq
  become: true
  gather_facts: false
  tags: [rabbitmq]
  roles:
    - rabbitmq

- name: Redis
  hosts: comp_redis
  become: true
  gather_facts: false
  tags: [redis]
  roles:
    - redis

#App Tier
- name: Catalogue
  hosts: comp_catalogue
  become: true
  gather_facts: false
  tags: [catalogue]
  roles:
    - catalogue

- name: Cart
  hosts: comp_cart
  become: true
  gather_facts: false
  tags: [cart]
  roles:
    - cart

- name: User
  hosts: comp_user
  become: true
  gather_facts: false
  tags: [user]
  roles:
    - user

- name: Shipping
  hosts: comp_shipping
  become: true
  gather_facts: false
  tags: [shipping]
  roles:
    - shipping

- name: Payment
  hosts: comp_payment
  become: true
  gather_facts: false
  tags: [payment]
  roles:
    - payment

- name: Dispatch
  hosts: comp_dispatch
  become: true
  gather_facts: false
  tags: [dispatch]
  roles:
    - dispatch

#Web Tier
- name: Web
  hosts: comp_web
  become: true
  gather_facts: false
  tags: [web]
  roles:
    - web
