---
# defaults file for shipping
service_name: shipping
mysql_host: "mysql.dev.optimusprime.uno"
mysql_root_password: "RoboShop@1"
mysql_root_host_pattern: "10.10.%"
shipping_packages:
  - maven
  - java-17-openjdk
  - mysql
shipping_artifact_url: "https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip"