---
# tasks file for mysql

# ------------------------------------------------------------
# 1) Roboshop Basic Requirements
# ------------------------------------------------------------
- name: Run Roboshop Application Basic Requirements
  ansible.builtin.import_role:
    name: common
    tasks_from: roboshop_basic_requirements.yml

# ------------------------------------------------------------
# 2) Copy MySQL 5.7 Repo
# ------------------------------------------------------------
- name: Copy MySQL Repo File
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
    owner: root
    group: root
    mode: "0644"

# ------------------------------------------------------------
# 3) Disable MySQL module
# ------------------------------------------------------------
- name: Disable MySQL module
  ansible.builtin.command: dnf module disable mysql -y
  changed_when: false
  failed_when: false

# ------------------------------------------------------------
# 4) Install MySQL 5.7
# ------------------------------------------------------------
- name: Install MySQL Server
  ansible.builtin.package:
    name: mysql-community-server
    state: present

# ------------------------------------------------------------
# 5) Enable and start MySQL
# ------------------------------------------------------------
- name: Enable and start MySQL
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

# ------------------------------------------------------------
# 6) Set root password
# ------------------------------------------------------------
- name: Set MySQL root password
  ansible.builtin.shell: |
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1'; FLUSH PRIVILEGES;"
  ignore_errors: true