---
- name: Ping All Roboshop Microservices (AWS Dynamic EC2 Inventory)
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Ping All EC2 Instances
      ansible.builtin.ping:
      register: ping_result
    - name: Print Ping Status
      ansible.builtin.debug:
        var: ping_result



